#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/venv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from main import wsgi_app

#
# Below for testing only
#
if __name__ == '__main__':
          
    from wsgiref.simple_server import make_server
    httpd = make_server('127.0.0.1', 8002, wsgi_app)
    # Wait for a single request, serve it and quit.
    httpd.handle_request()
